
spring:
  application:
    name: api-gateway
  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIG
      profile: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#server:
#  port: 9000
#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000
#zuul:
#  routes:
#    product: /myProduct/**
#    sensitiveHeaders:
#  ignored-patterns:
#    - /**/product/list
#    myProduct:
#      path: /myProduct/**
#      serviceId: product
#logging:
#  level:
#    org.springframework.web: trace
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#      health:
#        show-details: ALWAYS